# Temp for macOS and Tmux
export EVENT_NOKQUEUE=1

export MINIO_ACCESS_KEY=access_key_id
export MINIO_SECRET_KEY=secret_access_key

# Add postgresql 10 to path
export PATH="/usr/local/opt/postgresql@12/bin:$PATH"

# For Google Cloud SDK
if [[ -f /usr/local/var/google-cloud-sdk ]]; then
  source "/usr/local/var/google-cloud-sdk/completion.zsh.inc"
  source "/usr/local/var/google-cloud-sdk/path.zsh.inc"
fi

export NVIM_LISTEN_ADDRESS=127.0.0.1:6666
