tap "hashicorp/tap"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "maticzav/swift-graphql", "https://github.com/maticzav/swift-graphql.git"
tap "minio/stable"
tap "superfly/tap"

cask "keepingyouawake"
cask "raycast"
cask "ngrok"

brew "asdf"
brew "automake"
brew "bat"
brew "cmake"
brew "coreutils"
brew "fzf"
brew "gettext"
brew "gh"
brew "git"
brew "glib"
brew "gnu-sed"
brew "hashicorp/tap/packer"
brew "hashicorp/tap/terraform"
brew "hashicorp/tap/terraform-ls"
brew "hashicorp/tap/waypoint"
brew "heroku/brew/heroku"
brew "htop"
brew "imagemagick"
brew "innoextract"
brew "jid"
brew "jq"
brew "krb5"
brew "libtermkey"
brew "libtool"
brew "libuv"
brew "libvterm"
brew "maticzav/swift-graphql/swiftgraphql"
brew "minio", restart_service: false
brew "mitmproxy"
brew "msgpack"
brew "neovim"
brew "nmap"
brew "pkg-config"
brew "poppler"
brew "postgresql@13", restart_service: true
brew "pyenv"
brew "python@3.9"
brew "qt"
brew "redis", restart_service: true
brew "ripgrep"
brew "shared-mime-info"
brew "sqlite"
brew "starship"
brew "superfly/tap/flyctl"
brew "swiftformat"
brew "the_silver_searcher"
brew "tldr"
brew "tmux"
brew "tokei"
brew "vips"
brew "wget"
brew "z"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
