#!/usr/bin/env bash

set -e

# Create symlinks
cd "$HOME"
[ ! -L icloud-drive ] && ln -s "$HOME/Library/Mobile Documents/com~apple~CloudDocs" icloud-drive

files=(
  .bin
  .gitconfig
  .ideavimrc
  .psqlrc
  .tmux.conf
  .tmuxinator
  .vscode
)
for link in ${files[@]}; do
  if [ -L "$HOME/$link" ]; then
    echo "Link '$link' already exists"
  else
    ln -s "icloud-drive/dotfiles/$link" .
  fi
done

# Link nvim config
mkdir -p "$HOME/.config"
cd "$HOME/.config"
[ ! -L fish ] && ln -s ../icloud-drive/dotfiles/.config/fish .

[ ! -L nvim ] && mkdir nvim
[ ! -L nvim/init.lua ] && ln -s ../icloud-drive/dotfiles/.config/nvim/init.lua nvim/init.lua
[ ! -L nvim/autoload ] && ln -s ../icloud-drive/dotfiles/.config/nvim/autoload nvim/autoload
[ ! -L nvim/coc-settings.json ] && ln -s ../icloud-drive/dotfiles/.config/nvim/coc-settings.json nvim/coc-settings.json

[ ! -L starship.toml ] && ln -s ../icloud-drive/dotfiles/.config/starship.toml .
cd ..

# Link .ssh config
mkdir -p "$HOME/.ssh"
cd "$HOME/.ssh"
[ ! -L config ] && ln -s ../icloud-drive/dotfiles/.ssh/config .
cd ..

# Set macOS default hidden settings

## Disabling shadows on windows when taking screenshots - requires killall SystemUIServer
defaults write com.apple.screencapture disable-shadow -bool true

# Install things
if command -v brew; then
  echo "Homebrew already installed;"
else
  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# Install homebrew bundle
echo "Updating brew, running 'brew bundle', and upgrading packages"
brew update
brew tap Homebrew/bundle
brew bundle --verbose
brew upgrade
