version: 2
root-markers:
  - .git/
lint-debounce: 1s
log-file: /tmp/efm.log
log-level: 1

tools:
  # eruby-erb: &eruby-erb
  #   format-debounce: 2s
  #   format-stdin: true
  #   format-command: htmlbeautifier

  # tailwind-class-sort: &tailwind-class-sort
  #   format-command: "rustywind --stdin"
  #   format-stdin: true

  erb-format: &erb-format
    format-command: "erb-format --stdin --print-width=80 --tailwind-output=/Users/mikeastock/code/buildr/app/app/assets/builds/application.css"
    format-stdin: true

  rubyfmt: &rubyfmt
    format-stdin: true
    format-command: rubyfmt

  taplo: &taplo
    format-stdin: true
    format-command: "taplo fmt --option reorder_keys=true -"

languages:
  # ruby:
  #   - <<: *rubyfmt
  html:
    - <<: *erb-format
  eruby:
    # - <<: *eruby-erb
    - <<: *erb-format
  toml:
    - <<: *taplo
