version: 2
root-markers:
  - .git/
lint-debounce: 1s
log-file: /tmp/efm.log
log-level: 1

tools:
  eruby-erb: &eruby-erb
    format-debounce: 2s
    format-stdin: true
    format-command: htmlbeautifier

  tailwind-class-sort: &tailwind-class-sort
    format-command: "rustywind --stdin"
    format-stdin: true

  rubyfmt: &rubyfmt
    format-stdin: true
    format-command: rubyfmt

languages:
  # ruby:
  #   - <<: *rubyfmt
  html:
    - <<: *tailwind-class-sort
  eruby:
    # - <<: *eruby-erb
    - <<: *tailwind-class-sort
