version: 2
root-markers:
  - .git/
lint-debounce: 1s
log-file: /tmp/efm.log
log-level: 1

tools:
  eruby-erb: &eruby-erb
    format-debounce: 2s
    format-stdin: true
    format-command: htmlbeautifier

  rubyfmt: &rubyfmt
    format-stdin: true
    format-command: rubyfmt

languages:
  # ruby:
  #   - <<: *rubyfmt
  eruby:
    - <<: *eruby-erb
