version: 2
root-markers:
  - .git/
lint-debounce: 1s
log-file: /tmp/efm.log
log-level: 1

tools:
  erb-format: &erb-format
    format-command: "erb-format --stdin --print-width=80 --no-split-classes"
    format-stdin: true

  rubyfmt: &rubyfmt
    format-stdin: true
    format-command: rubyfmt

  taplo: &taplo
    format-stdin: true
    format-command: "taplo fmt --option reorder_keys=true -"

languages:
  # ruby:
  #   - <<: *rubyfmt

  html:
    - <<: *erb-format

  eruby:
    - <<: *erb-format

  toml:
    - <<: *taplo
