#!/bin/bash

set -e

brew update
brew upgrade --all
brew reinstall --HEAD fzf neovim

pushd ~/.rbenv
  git pull
  pushd ~/.rbenv/plugins
    for plugin in *; do
      pushd "$plugin"
        git pull
      popd
    done
  popd
popd

nvim +PlugUpgrade +PlugUpdate +qa
