#!/bin/zsh

if [ ! -e $HOME/.vim/autload/plug.vim ]; then
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
if [ ! -e $HOME/.nvim/autload/plug.vim ]; then
  curl -fLo ~/.nvim/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
nvim -u $HOME/.vimrc.plugins +PlugInstall +qall
