name: app
root: ./

windows:
  - nvim: nvim
  - git:
  - server:
      layout: 2311,208x101,0,0[208x55,0,0,2,208x33,0,56,3,208x11,0,90{104x11,0,90,4,103x11,105,90[103x7,105,90,5,103x3,105,98,6]}]
      panes:
        - DEMO_ENABLED=true rails server
        - DEMO_ENABLED=true be sidekiq
        - npm start
        - ngrok start minio closeout
