name: app
root: ./

windows:
  - nvim: nvim
  - git:
  - server:
      layout: dc1f,166x67,0,0[166x31,0,0,2,166x26,0,32,3,166x8,0,59,5]
      panes:
        - DEMO_ENABLED=true rails server
        - DEMO_ENABLED=true be sidekiq
        - ngrok start minio closeout
