#!/usr/bin/env python3
"""Refresh local TypeScript declarations for Amp plugin development."""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "types" / "ampcode-plugin.d.ts"


def main() -> int:
    try:
        docs = subprocess.check_output(
            ["amp", "plugins", "show-docs"],
            cwd=ROOT,
            stderr=subprocess.STDOUT,
            text=True,
        )
    except FileNotFoundError:
        print("error: amp CLI not found in PATH", file=sys.stderr)
        return 127
    except subprocess.CalledProcessError as exc:
        print(exc.output, file=sys.stderr, end="")
        return exc.returncode

    marker = "declare module '@ampcode/plugin' {"
    start = docs.find(marker)
    if start == -1:
        print("error: amp plugins show-docs did not include @ampcode/plugin declarations", file=sys.stderr)
        return 1

    declarations = docs[start:].rstrip() + "\n"
    header = """// Generated by scripts/update_amp_plugin_types.py.
// Do not edit by hand; run `make amp-plugin-types` or `pnpm amp:plugin-types`.

"""

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(header + declarations)
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
