# Allow [ or ] whereever you want
unsetopt nomatch

# use vim as the visual editor
export VISUAL=vim
export EDITOR=$VISUAL
export DISABLE_AUTO_TITLE=true
export GOPATH=$HOME/gocode

# tmuxinator
source ~/.bin/tmuxinator.zsh

# aliases
[[ -f ~/.aliases ]] && source ~/.aliases

# fuctions
zstyle ':completion:*:*:git:*' script ~/.zsh/git-completion.zsh
zstyle ':completion:*:*:git:*' user-commands ${${(M)${(k)commands}:#git-*}/git-/}

# paths
export PATH=/usr/local/rbenv/shims:/usr/local/rbenv/bin:/usr/local/redis/bin:/usr/local/pgsql/bin:./bin:/usr/local/ABBYYOCR11:/home/mikeastock/.linuxbrew/bin:$GOPATH/bin:$PATH
export RBENV_ROOT="/usr/local/rbenv"
eval "$(rbenv init - --no-rehash)"

export LD_LIBRARY_PATH=/usr/local/ABBYYOCR11

function git_prompt_info() {
  ref=$(git symbolic-ref HEAD 2> /dev/null) || return
  echo "$ZSH_THEME_GIT_PROMPT_PREFIX${ref#refs/heads/}$ZSH_THEME_GIT_PROMPT_SUFFIX"
}

export NVM_DIR="/home/mikeastock/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"  # This loads nvm

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
