# Allow completing of the remainder of a command
bindkey "^N" insert-last-word

# Save a ton of history
HISTSIZE=20000
HISTFILE=~/.zsh_history
SAVEHIST=20000

# Enable completion
zstyle ':completion:*' list-colors "${(@s.:.)LS_COLORS}"
autoload -Uz compinit
compinit

# CTRL-A and CTRL-E
bindkey -e

# Allow [ or ] whereever you want
unsetopt nomatch

# Disable flow control commands (keeps C-s from freezing everything)
stty start undef
stty stop undef

# Sourcing of other zsh files
source $HOME/.dotfiles/files/zsh/aliases
source $HOME/.dotfiles/files/zsh/functions
source $HOME/.dotfiles/files/zsh/prompt

export PATH="/usr/local/rbenv/bin:/usr/local/rbenv/shims:/usr/local/bin:$PATH"

# Load rbenv
eval "$(rbenv init - )"
